arpa2dns: Does not crash at a whim  - it is still a blemish on the shell system... but does not crash it  - it may fail loading libraries (version differences Python / Debian)  - it will then complain that it is DYSFUNCT and that you should BAIL OUT  - do anything to DNS and it will still crash if DYSFUNCT  - it now assumes that Knot is already started, and does not run #TESTCODE#
There also seems to be a problem with libknot itself:

.../libknot-2.9.2-py3.7.egg/libknot/control.py", line 189, in __del__
AttributeError: 'KnotCtl' object has no attribute 'obj'